### ISSUE TITLE
Raise exception on wiringPi failure

### ISSUE THREAD

**Issue by Gadgetoid** [WiringPi/WiringPi-Python#28]
Issue copied from: https://github.com/Gadgetoid/WiringPi2-Python/issues/33

@elegantandrogyne wrote:

Test case:

`import wiringpi2 as wiringpi`
`wiringpi.mcp23017Setup(65, 0x20)`

Works on a Raspberry with mcp23017, crashes to shell otherwise.
wiringPi output on Raspberry without mcp23017:

`Unable to open I2C device: No such file or directory`

wiringPi output on non-Raspberry (e.g. Lenovo T61p with Debian stretch):

`piBoardRev: Unable to determine board revision from /proc/cpuinfo`
`-> No "Hardware" line`
`->  You may want to check:`
`->  http://www.raspberrypi.org/phpBB3/viewtopic.php?p=184410#p184410`

Is it possible to raise an exception whenever wiringPi exits with EXIT_FAILURE status (with whatever it prints to stderr in the exception message) instead of crashing?
(current version of wiringPi has 22 places where it happens: https://git.drogon.net/?p=wiringPi&a=search&h=HEAD&st=grep&s=EXIT_FAILURE )

**Comment by liffiton** [comment]
[long overdue update:]

It is possible to translate the hard exits into exceptions with some [hacky hacks](https://stackoverflow.com/questions/34043652/calling-exit-in-c-library-terminates-python-script-that-wrapps-that-library), but I'm not sure it's worth it.  The wiringPi library calls `exit()` in cases where it has been used incorrectly or otherwise can't continue in what it has been asked to do, so it seems that any Python code that triggers those conditions could be fixed.  If there is some use case where having a Python script continue even after it has caused wiringPi to exit with a failure, feel free comment here and we can reopen this, but for now I'm going to close it.

[Also, for the specific example of calling `mcp23017Setup()`: I think that only exits out if `/dev/i2c-1` doesn't exist, which I think is controlled by enabling/disabling I2C in `raspi-config`.]
