### ISSUE TITLE
Working Interrupts

### ISSUE THREAD

**Issue by pacmac** [WiringPi/WiringPi-Python#5]
Is it possible to get interrupts working in your fork ?

https://github.com/Gadgetoid/WiringPi2-Python/issues/8

**Comment by elegantandrogyne** [comment]
I'm no good at C, but maybe this will help:
https://docs.python.org/release/2.5.2/ext/callingPython.html

**Comment by Gadgetoid** [comment]
@elegantandrogyne that's actually somewhat useful- it lets me conceptualize how interrupts might be implemented.

Basically, the problem is this; Passing a Python function into a C function is impossible. There's no way around that. There is simply no way to magically translate Python into a C function reference, and even SWIG can't overcome that problem. ( from everything I've read )

However, the document you link poses a solution- while I can't go rooting around in the guts of WiringPi changing how it works to accept Python functions, I *could* create a new set of functions which live outside of WiringPi ( keeping the dependency separate and maintainable ) but which store the Python functions somewhere and provide a C function that wraps up the call to them.

Broadly speaking I'd expect some collection object to provide a place for Python callbacks to live, let's call it PyISRCallbacks[NUM_PINS].

When you call the new function - ISR(pin, mode, python_function) - it will store as follows: PyISRCallbacks[pin] = python_function

It will then call wiringPiISR() and pass it a C function which wraps up the appropriate code for calling the Python handler.

This is all hypothetical, and slightly out of my depth, but I think it's possible.

**Comment by Gadgetoid** [comment]
Looking at the resources provided above, and RPi.GPIO as a canonical example I have in my mind what I think will be a viable working solution for interrupts.

I think the solution is a new shim between WiringPi and my bindings which contains a C function entitled wiringPiPythonISR. This will accept a pin, an edge and, specifically, a Python object- ie: a Python function.

It will then store the Python function in much the same way as RPi.GPIO does now ( which is the same solution proposed in the docs above ) - http://sourceforge.net/p/raspberry-gpio-python/code/ci/default/tree/source/py_gpio.c#l655
 
Once stored, it will then call wiringPiISR with an internal C function that does nothing but redirect the interrupt request to the requisite Python function.

**Comment by willprice** [comment]
Hi Gadgetoid,

> There is simply no way to magically translate Python into a C function reference, and even SWIG can't overcome that problem. ( from everything I've read )

Well... in the most literal sense that is correct, however we can call functions from each language in the other... the problem is of dynamically figuring out type signatures at run time, something I'm not sure is possible. In this specific instance we don't care so much about functions of any type, since this is a callback for the ISR routine it doesn't need any parameters. We just need to write functions that adhere to an interface and then SWIG can call them (if my understanding is correct) since it'll use dynamic despatch (virtual methods).

I need this functionality and have been looking into how to implement it... a few websites you'll find of use:
[Cross language polymorphism in SWIG](http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_directors)
[Example of callbacks using SWIG's directors](https://github.com/swig/swig/tree/master/Examples/python/callback)
[Hand rolled callbacks](https://gist.github.com/oliora/3607799)


If I manage to figure it out, I'll send a pull request over :)

**Comment by mickeys27** [comment]
hello
sorry for my english i am french
i try this function 
wiringpi.wiringPiISR(70,int(3), my_int)
but
TypeError: in method 'wiringPiISR', argument 3 of type 'void (*)(void)'

When you think to implant this interrupt on python
do you have a deadline ?

with gpio i use add_event_detect  but have mcp23017 and i use wiringpi2 with python
and I can't use add_event_detect

thanck you

**Comment by willprice** [comment]
Hey,
`wiringpi.wiringPiISR(70,int(3), my_int)` is never going to work. I've been looking at writing an interface in C++ and injecting callbacks through this however it is causing segfaults in the interpreter (probably due to the callback being called from another thread), I'm not sure whether I'm going to be making much progress with this as `RPi.GPIO` can be used in addition to `wiringpi2` to work with interrupts, it's not pretty, but at least it works.

**Comment by mickeys27** [comment]
do you have a exemple ?

**Comment by willprice** [comment]
Look up the examples on the RPi.Gpio wiki

**Comment by mickeys27** [comment]
sorry i don't find a solution 

maybe to call c++ function on python ?

**Comment by speendo** [comment]
I had a similar problem and solved it with some Python code somehow bypassing most of wiringPi. Find it here:

https://github.com/speendo/Photocell

In my understanding this is maybe more like a workaround than an actual solution. However, it works in my usecase and I hope it might help other people coming to this point.

**Comment by nalajcie** [comment]
Hi,
I've just created pull request implementing this functionality: https://github.com/WiringPi/WiringPi2-Python/pull/24
